export const URL:string  = 'http://localhost:3113/quiz/'

export const GET_QUIZES: string = 'GET_QUIZES'
export const SET_QUIZ_NAME: string = 'SET_QUIZ_NAME'
export const DELETE_QUIZ: string = 'DELETE_QUIZ'
export const ADD_QUIZ: string = 'ADD_QUIZ'
export const OPEN_MODAL_ADD_QUIZ: string = 'OPEN_MODAL_ADD_QUIZ'
export const CLOSE_MODAL_ADD_QUIZ: string = 'CLOSE_MODAL_ADD_QUIZ'
export const OPEN_MODAL_ADD_QUESTION: string = 'OPEN_MODAL_ADD_QUESTION'
export const CLOSE_MODAL_ADD_QUESTION: string = 'CLOSE_MODAL_ADD_QUESTION'
export const SAVE_QUESTION: string = 'SAVE_QUESTION'
export const DELETE_QUESTION: string = 'DELETE_QUESTION'
export const RESET: string = 'RESET'
export const SELECT_QUIZ: string = 'SELECT_QUIZ'
export const SET_EDIT_MODE: string = 'SET_EDIT_MODE'
export const SET_QUESTION_ID: string = 'SET_QUESTION_ID'
export const UPDATE_QUESTIONS: string = 'UPDATE_QUESTIONS' 
export const SET_EDIT_QUESTION: string = 'SET_EDIT_QUESTION'
export const UPDATE_SINGLE_QUESTION: string = 'UPDATE_SINGLE_QUESTION'
export const UPDATE_QUIZ: string = 'UPDATE_QUIZ'
export const RESET_SINGLE_QUESTION: string = 'RESET_SINGLE_QUESTION'

// messages
export const OK: string = 'ok'
export const FETCH_ERROR: string = 'Error getting quizes...' 
export const DELETION_ERROR: string = 'Deletion ID error...' 
export const HIDE: string = 'Hide' 
export const SHOW_ANSWER: string = 'Show answer' 
export const END: string = 'End' 
export const SERVER_ERROR: string = 'SERVER ERROR'
export const URL_ERROR: string = 'URL ERROR'
export const ADDING_QUIZ_SUCCESS: string = 'Successfully added quiz'
export const ERROR_ADDING_QUIZ = 'Error adding quiz'
export const ERROR_UPDATING_QUIZ = 'Error updating quiz'
export const UPDATING_QUIZ_SUCCESS = 'Successfully updated quiz'
export const EMPTY_WARNING: string = 'Please, check you data'


